#!/usr/bin/ruby
require 'rubygems'
require 'bundler/setup'
require 'json'
require 'yaml'
require 'faraday'

CONFIG = YAML.load_file('config.yml')
API_URL = 'https://seevogh.com/'
ACTIVE_PATH = 'api/reporting/getActivMeetings'
PAST_PATH = 'api/reporting/getPastMeetings'
STATUS_PATH= "api/meeting/status"

def past?
  ARGV[1] == "--past"
end

conn = Faraday.new(url: API_URL) do |faraday|
  faraday.request  :url_encoded             # form-encode POST params
  faraday.response :logger                  # log requests to STDOUT
  faraday.adapter  Faraday.default_adapter  # make requests with Net::HTTP
end

if past? || ARGV[1].nil?
  resp = conn.post past? ? PAST_PATH : ACTIVE_PATH, {
    "apiLogin" => CONFIG['login'],
    "apiPassword" => CONFIG['password']
  }
else
  resp = conn.post STATUS_PATH, {
    "apiLogin" => CONFIG['login'],
    "apiPassword" => CONFIG['password'],
    "meetingId" => ARGV[1]
  }
end


puts resp.body
